apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-prod-deployer
  namespace: prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-prod-role
  namespace: prod
rules:
- apiGroups: ["", "apps"]
  resources:
    - deployments
    - services
    - pods
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-prod-binding
  namespace: prod
subjects:
- kind: ServiceAccount
  name: jenkins-prod-deployer
  namespace: prod
roleRef:
  kind: Role
  name: jenkins-prod-role
  apiGroup: rbac.authorization.k8s.io